[nginx-boshrelease] start bosh shipit v2

diff --git a/ci/scripts/shipit b/ci/scripts/shipit
--- a/ci/scripts/shipit
+++ b/ci/scripts/shipit
@@ -24,38 +24,32 @@ if [[ -z ${VERSION} ]]; then
   exit 2
 fi
 
-if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
-  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
-  exit 1
-fi
+#if [[ ! -f ${REPO_ROOT}/ci/release_notes.md ]]; then
+#  echo >&2 "ci/release_notes.md not found.  Did you forget to write them?"
+#  exit 1
+#fi
 
 ###############################################################
 
-cat > ~/.bosh_config << EOF
----
-aliases:
-  target:
-    bosh-lite: ${BOSH_LITE_TARGET}
-auth:
-  ${BOSH_LITE_TARGET}:
-    username: ${BOSH_LITE_USERNAME}
-    password: ${BOSH_LITE_PASSWORD}
-EOF
 cat > ${REPO_ROOT}/config/private.yml << EOF
 ---
 blobstore:
   s3:
     access_key_id: ${AWS_ACCESS_KEY}
     secret_access_key: ${AWS_SECRET_KEY}
+    endpoint: http://10.244.0.22:9001
 EOF
-bosh target ${BOSH_LITE_TARGET}
+export BOSH_CA_CERT=${BOSH_CA_CERT}
+export BOSH_CLIENT=${BOSH_USERNAME}
+export BOSH_CLIENT_SECRET=${BOSH_PASSWORD}
+
 (cd ${REPO_ROOT}
- bosh -n create release --final --with-tarball --version "${VERSION}")
+ bosh -n create-release --final --tarball=${REPO_ROOT}/releases/${RELEASE_NAME}/${RELEASE_NAME}-${VERSION}.tgz --version "${VERSION}")
 
 mkdir -p ${RELEASE_ROOT}/artifacts
 echo "v${VERSION}"                         > ${RELEASE_ROOT}/tag
 echo "${RELEASE_NAME} v${VERSION}"         > ${RELEASE_ROOT}/name
-mv ${REPO_ROOT}/ci/release_notes.md          ${RELEASE_ROOT}/notes.md
+#mv ${REPO_ROOT}/ci/release_notes.md          ${RELEASE_ROOT}/notes.md
 cp ${REPO_ROOT}/releases/*/*-${VERSION}.tgz  ${RELEASE_ROOT}/artifacts
 
 cat > ${RELEASE_ROOT}/notification <<EOF
@@ -64,18 +58,18 @@ EOF
 
 
 # GIT!
-if [[ -z $(git config --global user.email) ]]; then
-  git config --global user.email "ci@starkandwayne.com"
-fi
-if [[ -z $(git config --global user.name) ]]; then
-  git config --global user.name "CI Bot"
-fi
-
-(cd ${REPO_ROOT}
- git merge --no-edit ${BRANCH}
- git add -A
- git status
- git commit -m "release v${VERSION}")
+#if [[ -z $(git config --global user.email) ]]; then
+#  git config --global user.email "ci@starkandwayne.com"
+#fi
+#if [[ -z $(git config --global user.name) ]]; then
+#  git config --global user.name "CI Bot"
+#fi
+#
+#(cd ${REPO_ROOT}
+# git merge --no-edit ${BRANCH}
+# git add -A
+# git status
+# git commit -m "release v${VERSION}")
 
 # so that future steps in the pipeline can push our changes
 cp -a ${REPO_ROOT} ${REPO_OUT}
